### ISSUE TITLE
Cannot build the network component

### ISSUE THREAD

**Issue by cyan33** [thomasyimgit/zion#9]
```sh
ERROR in ./node_modules/socket.io/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/changyan/Documents/repos/zion/node_modules/socket.io/lib'
 @ ./node_modules/socket.io/lib/index.js 7:11-24 9:13-26
 @ ./src/network.js
 @ ./src/index.js
 @ multi ./src/index.js ./src/index.js ./dist/zion.js
```

**Comment by cyan33** [comment]
The network is removed due to following reasons:

1. the network component API is rather poor, deterministic and not flexible enough
2. there is a bundling error which I still haven't figured a way to have it bundled into the dist files

We may still add it in the future tho

**Comment by karneaud** [comment]
Is the network feature available??? why not try decoupling and plugin with http://serverjs.io
